# Generated by Django 5.2.6 on 2025-10-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_failed', 'Payment Failed'), ('pending_acceptance', 'Pending Accept'), ('rejected', 'Rejected'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready For Pick'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending_payment', max_length=32)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
